version: 2.1

orbs:
  php: circleci/php@1.0
  wp-svn: studiopress/wp-svn@0.1

workflows:
  test-deploy:
    jobs:
      - php/test:
          test-command: phpcs
      - approval-for-deploy-tested-up-to-bump:
          type: approval
          requires:
            - php/test
          filters:
            tags:
              ignore: /.*/
            branches:
              only: /^bump-tested-up-to.*/
      - wp-svn/deploy-tested-up-to-bump:
          context: genesis-svn
          requires:
            - approval-for-deploy-tested-up-to-bump
