version: 2.1

orbs:
  php: circleci/php@1.0
  wp-svn: studiopress/wp-svn@0.1

jobs:
  svn-test:
    docker:
      - image: cimg/base:current
    steps:
      - checkout:
          path: /tmp/src
      - run:
          name: Testing
          command: |
            CHECKOUT_PATH=/tmp/src

            SLUG=$CIRCLE_PROJECT_REPONAME
            if [ ! $SLUG ]
              then
              echo "Didn't find the plugin slug from the repo name"
              exit 1
            fi

            echo "The slug is $SLUG"

            echo "The grep produces:"
            grep -i 'Version:' $CHECKOUT_PATH/*.php
            VERSION=$(grep -i 'Version:' $CHECKOUT_PATH/*.php | awk -F: '{print $3}' | sed 's/^\s//')
            if [ ! $VERSION ]
              then
              echo "Didn't find a version of the plugin"
              exit 1
            fi

            echo "The version is $VERSION"
            TESTED_UP_TO_VERSION=$(grep -i 'tested up to:' $CHECKOUT_PATH/readme.txt | awk -F: '{print $2}' | sed 's/^\s//')
            if [ ! $TESTED_UP_TO_VERSION ]
              then
              echo "Didn't find a 'Tested up to' version, so can't bump it"
              exit 1
            fi

workflows:
  test-deploy:
    jobs:
      - svn-test
      - php/test:
          test-command: phpcs
      - approval-for-deploy-tested-up-to-bump:
          type: approval
          requires:
            - php/test
          filters:
            tags:
              ignore: /.*/
            branches:
              only: /^bump-tested-up-to.*/
      - wp-svn/deploy-tested-up-to-bump:
          context: genesis-svn
          requires:
            - approval-for-deploy-tested-up-to-bump
